# Generated by Django 5.2.6 on 2026-04-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SOCJE", "SOCJE"),
                    ("SAFES", "SAFES"),
                    ("STE", "STE"),
                    ("SCS", "SCS"),
                ],
                max_length=100,
            ),
        ),
    ]
