# Generated by Django 4.2.23 on 2026-03-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('full_description', models.TextField()),
                ('proposal_type', models.CharField(choices=[('RESEARCH', 'Research'), ('EXTENSION', 'Extension')], default='RESEARCH', max_length=20)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('proposal_document', models.FileField(blank=True, null=True, upload_to='proposals/documents/')),
                ('budget_pdf', models.FileField(blank=True, null=True, upload_to='proposals/budgets/')),
                ('supporting_image', models.ImageField(blank=True, null=True, upload_to='proposals/images/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Proposal',
                'verbose_name_plural': 'Proposals',
                'ordering': ['-date_submitted'],
            },
        ),
    ]
