# Generated by Django 5.2.6 on 2026-03-11 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProposalDocumentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document",
                    models.FileField(upload_to="proposals/documents/versions/"),
                ),
                ("version_number", models.PositiveIntegerField(default=1)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("version_notes", models.TextField(blank=True)),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_versions",
                        to="proposals.proposal",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposal Document Version",
                "verbose_name_plural": "Proposal Document Versions",
                "ordering": ["-version_number"],
            },
        ),
    ]
