# Generated by Django 5.2.6 on 2026-04-24 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0003_proposaldocumentversion"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProposalRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requirement_key", models.CharField(max_length=100)),
                ("label", models.CharField(max_length=255)),
                ("is_custom", models.BooleanField(default=False)),
                (
                    "uploaded_file",
                    models.FileField(
                        blank=True, null=True, upload_to="proposals/requirements/"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(blank=True, null=True)),
                ("is_resubmitted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="proposals.proposal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposal Requirement",
                "verbose_name_plural": "Proposal Requirements",
                "ordering": ["created_at", "id"],
            },
        ),
    ]
