# Generated by Django 4.2.23 on 2026-05-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_two_stage_proposal_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='certificate_of_appearance',
            field=models.FileField(blank=True, null=True, upload_to='proposals/certificates/'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='certificate_of_participation',
            field=models.FileField(blank=True, null=True, upload_to='proposals/certificates/'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='certificate_of_publication',
            field=models.FileField(blank=True, null=True, upload_to='proposals/certificates/'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='conference_proceedings',
            field=models.FileField(blank=True, null=True, upload_to='proposals/proceedings/'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='full_paper',
            field=models.FileField(blank=True, null=True, upload_to='proposals/full_papers/'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='progress_report',
            field=models.FileField(blank=True, null=True, upload_to='proposals/progress_reports/'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='project_progress_status',
            field=models.CharField(blank=True, choices=[('ONGOING', 'Ongoing'), ('PRESENTED', 'Presented'), ('COMPLETED', 'Completed'), ('PUBLISHED', 'Published')], max_length=20),
        ),
    ]
