# Generated by Django 4.2.23 on 2026-05-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0006_proposal_certificate_of_appearance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='abstract_document',
            field=models.FileField(blank=True, null=True, upload_to='proposals/abstracts/'),
        ),
    ]
