# Generated by Django 4.2.23 on 2026-05-06 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposals', '0007_proposal_abstract_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalTrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('DOCUMENTS_UPLOADED', 'Documents Uploaded'), ('RECOMMENDED_APPROVAL', 'Recommended for Approval'), ('REVISION_REQUESTED', 'Revision Requested'), ('ADMIN_APPROVED', 'Approved by Admin'), ('ADMIN_REJECTED', 'Rejected by Admin'), ('RESUBMITTED', 'Resubmitted'), ('UPDATED', 'Updated')], max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('PENDING_RECOMMENDATION', 'Pending Staff Recommendation'), ('RECOMMENDED_APPROVAL', 'Recommended for Admin Approval'), ('RECOMMENDED_REVISION', 'Recommended for Revision'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=30)),
                ('document_label', models.CharField(blank=True, max_length=255)),
                ('document_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_tracking_events', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='proposals.proposal')),
            ],
            options={
                'verbose_name': 'Proposal Tracking Event',
                'verbose_name_plural': 'Proposal Tracking Events',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
