# Generated by Django 4.2.23 on 2026-03-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('SUSPENDED', 'Suspended'), ('PUBLISHED', 'Published')], default='ONGOING', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('funding_source', models.CharField(blank=True, max_length=255)),
                ('funding_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('output_description', models.TextField(blank=True)),
                ('publication_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Research Record',
                'verbose_name_plural': 'Research Records',
                'ordering': ['-start_date'],
            },
        ),
    ]
