# Generated by Django 4.2.23 on 2026-03-11 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchrecord',
            name='co_researchers',
            field=models.ManyToManyField(blank=True, related_name='research_coauthored', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='researchrecord',
            name='lead_researcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_lead', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='researchrecord',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_records', to='proposals.proposal'),
        ),
    ]
