# Generated by Django 5.2.6 on 2026-03-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchrecord",
            name="citation_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of times this research has been cited"
            ),
        ),
        migrations.AddField(
            model_name="researchrecord",
            name="citations_list",
            field=models.TextField(
                blank=True,
                help_text="List of sources that cited this research (APA/MLA format)",
            ),
        ),
        migrations.AddField(
            model_name="researchrecord",
            name="publication_year",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The year this research was officially published",
                null=True,
            ),
        ),
    ]
