# Generated by Django 4.2.23 on 2026-03-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('extension_type', models.CharField(choices=[('TRAINING', 'Training'), ('SEMINAR', 'Seminar'), ('WORKSHOP', 'Workshop'), ('OUTREACH', 'Outreach'), ('COMMUNITY_SERVICE', 'Community Service'), ('OTHER', 'Other')], default='COMMUNITY_SERVICE', max_length=30)),
                ('partner_community', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNING', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('beneficiary_count', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('output_documents', models.FileField(blank=True, null=True, upload_to='extension/documents/')),
                ('photos', models.ImageField(blank=True, null=True, upload_to='extension/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Extension Record',
                'verbose_name_plural': 'Extension Records',
                'ordering': ['-start_date'],
            },
        ),
    ]
