# Generated by Django 4.2.23 on 2026-03-11 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proposals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('extension', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionrecord',
            name='coordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_coordinated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extensionrecord',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extension_records', to='proposals.proposal'),
        ),
        migrations.AddField(
            model_name='extensionrecord',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='extension_participated', to=settings.AUTH_USER_MODEL),
        ),
    ]
