# Generated by Django 5.2.6 on 2026-03-13 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extension", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NarrativeReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quarter",
                    models.CharField(
                        choices=[
                            ("Q1", "1st Quarter (Jan-Mar)"),
                            ("Q2", "2nd Quarter (Apr-Jun)"),
                            ("Q3", "3rd Quarter (Jul-Sep)"),
                            ("Q4", "4th Quarter (Oct-Dec)"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "report_year",
                    models.PositiveIntegerField(
                        help_text="The year this report covers (e.g. 2024)"
                    ),
                ),
                (
                    "narrative",
                    models.TextField(
                        help_text="Detailed narrative report of activities, achievements, and issues."
                    ),
                ),
                ("date_submitted", models.DateTimeField(auto_now_add=True)),
                (
                    "extension_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="narrative_reports",
                        to="extension.extensionrecord",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_narratives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Narrative Report",
                "verbose_name_plural": "Narrative Reports",
                "ordering": ["-report_year", "-quarter"],
                "unique_together": {("extension_record", "quarter", "report_year")},
            },
        ),
    ]
